apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: passgen-site
  labels:
    app: passgen-site
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: passgen-site
    spec:
      containers:
        - name: passgen-site
          image: kristianwindsor/passgen.site
          ports:
            - containerPort: 80
