apiVersion: apps/v1
kind: Deployment
metadata:
  name: passgen
  labels:
    app: passgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passgen
  template:
    metadata:
      labels:
        app: passgen
    spec:
      containers:
        - name: passgen
          image: kristianwindsor/passgen.site
          ports:
            - containerPort: 80
